version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres_password # updated 6-12-2020
  redis:
    image: "redis:latest"
  nginx:
    restart: always # if other crashes, still work
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports: # local host
      - "3000:80"
  api: # express server
    build:
      dockerfile: Dockerfile.dev # just the file, no folder needed
      context: ./server # clarify the folder
    volumes:
      - /app/node_modules # create the app folder, dont overwrite this!
      - ./server:/app # copy server folder into app folder
    environment: # keys.js in server, variableName=value
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client: # react server
    stdin_open: true # otherwise, "React App exited with Code 0" error
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
